### ISSUE TITLE
Which PID should I choose?

### ISSUE THREAD

**Issue by Ashark** [xurubin/logitech_unifying_pid_patch#1]
Hi, very thanks for sharing these instructions.
I saw that you replaced 2BC5 with 2CC5 in your prepared file.
I guess you just randomly decided to choose it? Are there any suggestions for that? Maybe you need to choose some unexistent pid or oppositely choose some that exists?
In original post https://github.com/pwr/Solaar/issues/491 I have written a list of pids that I was able to find. Maybe I should use c532 for this purpose?
Do you have any downsides with such modified firmware? 
- Is it detected by your linux host as a unifying receiver?
- Does solaar work with it?
- Does your Windows guest detect it normally?
- Does Logitech Options work with it correctly?

**Comment by xurubin** [comment]
I only used the modified receiver in a Win7 VM and it's recognised as a generic USB composite device and generic keyboard/mouse. Never tried any Logitech specific features nor Solar on Linux.

**Comment by Ashark** [comment]
I have tested it. Solaar and Logitech Options (under win10 in virtualbox) cannot "see" receiver with pid=c52c. But mouse and keyboard were working correctly in both host and guest (they were previously paired).
That is why I asked about which pid is better to use. I guess that we need to use something known to the software? Or maybe it is oppositely should not be done because of some hardware differences? Just don't know.

**Comment by pfps** [comment]
Is there anything that needs to be done to Solaar for this issue?

**Comment by xurubin** [comment]
@pfps Thanks for the info regarding the other bug ("Without any guarantee, the safest changes would be ones that use the same setup in base_usb.py, i.e., c52b to c532 or c517 to c526."). I'll make a note in the readme.
