### ISSUE TITLE
Add determine receiver chip version info to readme

### ISSUE THREAD

**Issue by Ashark** [xurubin/logitech_unifying_pid_patch#4]
Please add to readme information about how to derermine which chip a unifying receiver is using.

It can be done with a simple command `fwupdmgr get-devices | grep "Unifying Receiver" -A3`
In this example I have inserted both receivers, and I can see which is Nordic based (firmware version RQR12) and which is TI based (firmware version RQR24)
```
$ fwupdmgr get-devices | grep "Unifying Receiver" -A3
├─Unifying Receiver:
│     Device ID:          a04d2149eebdb3eda67a37a2575ec263a8389cef
│     Summary:            A miniaturised USB wireless receiver
│     Current version:    RQR24.07_B0030
--
├─Unifying Receiver:
│     Device ID:          82091cc2e67e8e248d8dad9ac847708118484457
│     Summary:            A miniaturised USB wireless receiver
│     Current version:    RQR12.08_B0030
```

**Comment by xurubin** [comment]
Done! https://github.com/xurubin/logitech_unifying_pid_patch/commit/6ec374a02b57cd47962fb8bbb5e0fbc33572ce86
