### ISSUE TITLE
Problem in the instructions

### ISSUE THREAD

**Issue by Mehrdadma2008** [xurubin/logitech_unifying_pid_patch#5]
Hi, I ask you to help me a little more. I have two nano receiver dongles (VID_046D&PID_C52F&MI and VID_046D&PID_C534&MI), two K270 keyboards, and two M185 Mouses. one of dongle only works with one mouse and the other one support both keyboard and mouse. I want to modify the first dongle to support the other keyboard. is it possible to modify the dongle PID to solve my problem? If yes, which firmware version is better to use for this situation?

**Comment by xurubin** [comment]
Sorry I don't know if this is possible or not. If it's possible, it would be much more work than just tweaking the PID.
